import { OrdersManager } from "@/components/orders/orders-manager";
import {
  hasPermission,
  requireModuleAccess,
} from "@/lib/auth/permissions";
import { getOrdersPageData } from "@/lib/data/orders-page";
import { t } from "@/lib/i18n";
import { toOrderRow } from "@/lib/orders/serialize";
import {
  toCustomerRow,
  toPriceListRow,
  toSalesRepRow,
} from "@/lib/pricing/serialize";

export const dynamic = "force-dynamic";
export const revalidate = 0;
export const fetchCache = "force-no-store";

export default async function OrdersPage() {
  const { session, permissions } = await requireModuleAccess("orders");

  const capabilities = {
    canCreate: hasPermission(permissions, "orders", "create"),
    canEdit: hasPermission(permissions, "orders", "edit"),
    canDelete: hasPermission(permissions, "orders", "delete"),
    canSetPrice: session.canSetPrice,
    canApproveOrder: session.canApproveOrder,
  };

  const { orders, customers, salesReps, priceLists, products, orderProducts } =
    await getOrdersPageData();

  const labels: Record<string, string> = {
    title: t("modules.orders.title"),
    description: t("modules.orders.description"),
    ordersTab: t("orders.ordersTab"),
    customersTab: t("orders.customersTab"),
    salesRepsTab: t("orders.salesRepsTab"),
    priceListsTab: t("orders.priceListsTab"),
    customersList: t("orders.customersList"),
    salesRepsList: t("orders.salesRepsList"),
    priceListsList: t("orders.priceListsList"),
    records: t("orders.records"),
    customersShort: t("orders.customersShort"),
    searchPlaceholder: t("orders.searchPlaceholder"),
    newCustomer: t("orders.newCustomer"),
    newSalesRep: t("orders.newSalesRep"),
    newPriceList: t("orders.newPriceList"),
    selectCustomer: t("orders.selectCustomer"),
    selectSalesRep: t("orders.selectSalesRep"),
    selectPriceList: t("orders.selectPriceList"),
    name: t("orders.name"),
    company: t("orders.company"),
    cnpj: t("orders.cnpj"),
    region: t("orders.region"),
    salesRep: t("orders.salesRep"),
    noSalesRep: t("orders.noSalesRep"),
    priceList: t("orders.priceList"),
    noPriceList: t("orders.noPriceList"),
    paymentTerms: t("orders.paymentTerms"),
    address: t("orders.address"),
    phone: t("orders.phone"),
    email: t("orders.email"),
    code: t("orders.code"),
    channel: t("orders.channel"),
    channelRetail: t("orders.channelRetail"),
    channelCorporate: t("orders.channelCorporate"),
    channelPortal: t("orders.channelPortal"),
    listItems: t("orders.listItems"),
    listItemsDesc: t("orders.listItemsDesc"),
    itemsShort: t("orders.itemsShort"),
    product: t("orders.product"),
    boxPrice: t("orders.boxPrice"),
    unitPrice: t("orders.unitPrice"),
    save: t("orders.save"),
    create: t("orders.create"),
    saving: t("orders.saving"),
    created: t("orders.created"),
    saved: t("orders.saved"),
    saveError: t("orders.saveError"),
    connectionError: t("orders.connectionError"),
    itemsSaved: t("orders.itemsSaved"),
    saveItems: t("orders.saveItems"),
    tabInfo: t("orders.tabInfo"),
    tabPrices: t("orders.tabPrices"),
    tabPricesDesc: t("orders.tabPricesDesc"),
    tabTiers: t("orders.tabTiers"),
    tabTiersDesc: t("orders.tabTiersDesc"),
    tabCodes: t("orders.tabCodes"),
    tabCodesDesc: t("orders.tabCodesDesc"),
    tabTools: t("orders.tabTools"),
    tabToolsDesc: t("orders.tabToolsDesc"),
    addLine: t("orders.addLine"),
    addTier: t("orders.addTier"),
    addCode: t("orders.addCode"),
    savePrices: t("orders.savePrices"),
    saveTiers: t("orders.saveTiers"),
    saveCodes: t("orders.saveCodes"),
    pricesSaved: t("orders.pricesSaved"),
    tiersSaved: t("orders.tiersSaved"),
    codesSaved: t("orders.codesSaved"),
    thresholdQty: t("orders.thresholdQty"),
    discountPercent: t("orders.discountPercent"),
    unitBox: t("orders.unitBox"),
    unitPiece: t("orders.unitPiece"),
    externalSku: t("orders.externalSku"),
    skuResolve: t("orders.skuResolve"),
    priceResolve: t("orders.priceResolve"),
    resolve: t("orders.resolve"),
    skuNotFound: t("orders.skuNotFound"),
    priceNotFound: t("orders.priceNotFound"),
    newOrder: t("orders.newOrder"),
    orderNo: t("orders.orderNo"),
    orderNoAuto: t("orders.orderNoAuto"),
    customer: t("orders.customer"),
    freightType: t("orders.freightType"),
    deliveryDate: t("orders.deliveryDate"),
    orderLines: t("orders.orderLines"),
    quantityBoxes: t("orders.quantityBoxes"),
    quantityUnits: t("orders.quantityUnits"),
    unitPieceShort: t("orders.unitPieceShort"),
    lineTotal: t("orders.lineTotal"),
    margin: t("orders.margin"),
    orderDiscount: t("orders.orderDiscount"),
    freightAmount: t("orders.freightAmount"),
    subtotal: t("orders.subtotal"),
    orderTotal: t("orders.orderTotal"),
    saveDraft: t("orders.saveDraft"),
    submitApproval: t("orders.submitApproval"),
    approveOrder: t("orders.approveOrder"),
    toProduction: t("orders.toProduction"),
    backToKanban: t("orders.backToKanban"),
    importFromPdf: t("orders.importFromPdf"),
    importFromPdfHint: t("orders.importFromPdfHint"),
    importingPdf: t("orders.importingPdf"),
    importFromPdfSuccess: t("orders.importFromPdfSuccess"),
    importFromPdfError: t("orders.importFromPdfError"),
    orderEditorDesc: t("orders.orderEditorDesc"),
    kanbanDesc: t("orders.kanbanDesc"),
    pageIntro: t("orders.pageIntro"),
    workflowDraft: t("orders.workflowDraft"),
    workflowDraftDesc: t("orders.workflowDraftDesc"),
    workflowApproval: t("orders.workflowApproval"),
    workflowApprovalDesc: t("orders.workflowApprovalDesc"),
    workflowProduction: t("orders.workflowProduction"),
    workflowProductionDesc: t("orders.workflowProductionDesc"),
    workflowShip: t("orders.workflowShip"),
    workflowShipDesc: t("orders.workflowShipDesc"),
    statTotal: t("orders.statTotal"),
    statPending: t("orders.statPending"),
    statInProduction: t("orders.statInProduction"),
    statPipelineValue: t("orders.statPipelineValue"),
    kanbanEmpty: t("orders.kanbanEmpty"),
    sectionCustomer: t("orders.sectionCustomer"),
    sectionCustomerDesc: t("orders.sectionCustomerDesc"),
    sectionLines: t("orders.sectionLines"),
    sectionLinesDesc: t("orders.sectionLinesDesc"),
    sectionTotals: t("orders.sectionTotals"),
    sectionTotalsDesc: t("orders.sectionTotalsDesc"),
    ordersTabDesc: t("orders.ordersTabDesc"),
    customersTabDesc: t("orders.customersTabDesc"),
    salesRepsTabDesc: t("orders.salesRepsTabDesc"),
    priceListsTabDesc: t("orders.priceListsTabDesc"),
    notes: t("orders.notes"),
    statusUpdated: t("orders.statusUpdated"),
    statusError: t("orders.statusError"),
    analysisTab: t("orders.analysisTab"),
    orderFormTab: t("orders.orderFormTab"),
    historyTab: t("audit.historyTab"),
    historyTitle: t("audit.historyTitle"),
    historyDesc: t("audit.historyDesc"),
    noLogs: t("audit.noLogs"),
    systemUser: t("audit.systemUser"),
    lineAnalysis: t("orders.lineAnalysis"),
    lineAnalysisDesc: t("orders.lineAnalysisDesc"),
    required: t("orders.required"),
    fromStock: t("orders.fromStock"),
    toProduce: t("orders.toProduce"),
    batches: t("orders.batches"),
    revenue: t("orders.revenue"),
    prodCost: t("orders.prodCost"),
    materialCost: t("orders.materialCost"),
    laborCost: t("orders.laborCost"),
    laborEstimated: t("orders.laborEstimated"),
    expectedProfit: t("orders.expectedProfit"),
    materialNeeds: t("orders.materialNeeds"),
    materialNeedsDesc: t("orders.materialNeedsDesc"),
    noProductionNeeded: t("orders.noProductionNeeded"),
    requiredQty: t("orders.requiredQty"),
    availableQty: t("orders.availableQty"),
    shortage: t("orders.shortage"),
    ok: t("orders.ok"),
    totalRevenue: t("orders.totalRevenue"),
    totalProdCost: t("orders.totalProdCost"),
    totalLaborCost: t("orders.totalLaborCost"),
    totalMaterialCost: t("orders.totalMaterialCost"),
    totalOverheadCost: t("orders.totalOverheadCost"),
    overheadCost: t("orders.overheadCost"),
    overheadNote: t("orders.overheadNote"),
    overheadMethodKg: t("orders.overheadMethodKg"),
    overheadMethodHours: t("orders.overheadMethodHours"),
    totalExpectedProfit: t("orders.totalExpectedProfit"),
    startJob: t("orders.startJob"),
    shortageWarning: t("orders.shortageWarning"),
    loadingAnalysis: t("orders.loadingAnalysis"),
    analysisError: t("orders.analysisError"),
    unitBoxShort: t("orders.unitBoxShort"),
    ordersCreated: t("production.ordersCreated"),
    stockOnlyJobStarted: t("production.stockOnlyJobStarted"),
    createOrdersError: t("production.createOrdersError"),
  };

  return (
    <div className="mx-auto max-w-7xl">
      <OrdersManager
        initialOrders={orders.map(toOrderRow)}
        initialCustomers={customers.map(toCustomerRow)}
        initialSalesReps={salesReps.map(toSalesRepRow)}
        initialPriceLists={priceLists.map(toPriceListRow)}
        products={products}
        orderProducts={orderProducts.map((p) => ({
          id: p.id,
          sku: p.sku,
          name: p.name,
          unitsPerBox: p.packaging?.unitsPerBox ?? 0,
          packagingCode: p.packaging?.code ?? null,
          customerId: p.customerId,
        }))}
        salesReps={salesReps.map(toSalesRepRow)}
        priceLists={priceLists.map(toPriceListRow)}
        capabilities={capabilities}
        labels={labels}
      />
    </div>
  );
}
